In [69]:
import pandas as pd

In [70]:
caminho = r"H:\python\analise_de_dados\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [71]:
tabela = pd.read_excel(caminho, header=2)
tabela

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
dados_trabalhados = tabela.iloc[0:5570,1:]

In [73]:
dados_trabalhados["diferença"] = (dados_trabalhados["População Censo 2022"] - dados_trabalhados["População Município 2010\n(Sinopse)"])
dados_trabalhados

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferença
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,-2898.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0,6480.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0,-962.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0,8313.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0,-1139.0
...,...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0,2408.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0,1397.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0,-520.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0,670.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,247221.0

In [74]:
dados_trabalhados.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'diferença'],
      dtype='str')

In [84]:
porestado = (
    dados_trabalhados.groupby('UF')[[
        'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'diferença']]
    .sum()
    .reset_index()
)
porestado

,UF,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferença
0,AC,733559.0,733559.0,830018.0,96459.0
1,AL,3120494.0,3120887.0,3127683.0,7189.0
2,AM,3483985.0,3483985.0,3941613.0,457628.0
3,AP,669526.0,669526.0,733759.0,64233.0
4,BA,14016906.0,14017071.0,14141626.0,124720.0
5,CE,8452381.0,8451644.0,8794957.0,342576.0
6,DF,2570160.0,2572159.0,2817381.0,247221.0
7,ES,3514952.0,3514952.0,3833712.0,318760.0
8,GO,6003788.0,6001789.0,7056495.0,1052707.0
9,MA,6574789.0,6574789.0,6776699.0,201910.0
10,MG,19597330.0,19597330.0,20539989.0,942659.0
11,MS,2449024.0,2449024.0,2757013.0,307989.0
12,MT,3035122.0,3035122.0,3658649.0,623527.0
13,PA,7581051.0,7581051.0,8120131.0,539080.0
14,PB,3766528.0,3766528.0,3974687.0,208159.0
15,PE,8796448.0,8796055.0,9058931.0,262483.0
16,PI,3118360.0,3119097.0,3271199.0,152839.0
17,PR,10444526.0,10444526.0,11444380.0,999854.0
18,RJ,15989929.0,15989929.0,16055174.0,65245.0
19,RN,3168027.0,3168027.0,3302729.0,134702.0
20,RO,1562409.0,1562409.0,1581196.0,18787.0
21,RR,450479.0,450479.0,636707.0,186228.0
22,RS,10693929.0,10693929.0,10882965.0,189036.0
23,SC,6248436.0,6248436.0,7610361.0,1361925.0
24,SE,2068017.0,2067852.0,2210004.0,141987.0
25,SP,41262199.0,41262199.0,44411238.0,3149039.0
26,TO,1383445.0,1383445.0,1511460.0,128015.0

In [97]:
porestado = porestado.sort_values(by='diferença', ascending=False)
porestado

,UF,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferença
25,SP,41262199.0,41262199.0,44411238.0,3149039.0
23,SC,6248436.0,6248436.0,7610361.0,1361925.0
8,GO,6003788.0,6001789.0,7056495.0,1052707.0
17,PR,10444526.0,10444526.0,11444380.0,999854.0
10,MG,19597330.0,19597330.0,20539989.0,942659.0
12,MT,3035122.0,3035122.0,3658649.0,623527.0
13,PA,7581051.0,7581051.0,8120131.0,539080.0
2,AM,3483985.0,3483985.0,3941613.0,457628.0
5,CE,8452381.0,8451644.0,8794957.0,342576.0
7,ES,3514952.0,3514952.0,3833712.0,318760.0
11,MS,2449024.0,2449024.0,2757013.0,307989.0
15,PE,8796448.0,8796055.0,9058931.0,262483.0
6,DF,2570160.0,2572159.0,2817381.0,247221.0
14,PB,3766528.0,3766528.0,3974687.0,208159.0
9,MA,6574789.0,6574789.0,6776699.0,201910.0
22,RS,10693929.0,10693929.0,10882965.0,189036.0
21,RR,450479.0,450479.0,636707.0,186228.0
16,PI,3118360.0,3119097.0,3271199.0,152839.0
24,SE,2068017.0,2067852.0,2210004.0,141987.0
19,RN,3168027.0,3168027.0,3302729.0,134702.0
26,TO,1383445.0,1383445.0,1511460.0,128015.0
4,BA,14016906.0,14017071.0,14141626.0,124720.0
0,AC,733559.0,733559.0,830018.0,96459.0
18,RJ,15989929.0,15989929.0,16055174.0,65245.0
3,AP,669526.0,669526.0,733759.0,64233.0
20,RO,1562409.0,1562409.0,1581196.0,18787.0
1,AL,3120494.0,3120887.0,3127683.0,7189.0

In [98]:
porestado.to_csv(r"H:\python\analise_de_dados\Ctabelaminhaatividade4.csv", sep =";")

In [82]:
pormunicipio = (
    dados_trabalhados.groupby('NOME DO MUNICÍPIO')[[
        'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'diferença']]
    .sum()
    .reset_index()
)
pormunicipio

,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferença
0,Abadia de Goiás,6876.0,6891.0,19128.0,12252.0
1,Abadia dos Dourados,6704.0,6704.0,6272.0,-432.0
2,Abadiânia,15757.0,15759.0,17232.0,1475.0
3,Abaetetuba,141100.0,141100.0,158188.0,17088.0
4,Abaeté,22690.0,22690.0,22675.0,-15.0
...,...,...,...,...,...
5292,Áurea,3665.0,3665.0,3396.0,-269.0
5293,Ângulo,2859.0,2859.0,3235.0,376.0
5294,Érico Cardoso,10859.0,10882.0,10604.0,-255.0
5295,Óbidos,49333.0,49333.0,52229.0,2896.0
5296,Óleo,2673.0,2673.0,2512.0,-161.0

In [94]:
pormunicipi = tabela.iloc[0:5570,3:]
pormunicipi["diferença"] = (pormunicipi["População Censo 2022"] - pormunicipi["População Município 2010\n(Sinopse)"])
pormunicipi

,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferença
0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,-2898.0
1,23.0,Ariquemes,90353.0,90353.0,96833.0,6480.0
2,31.0,Cabixi,6313.0,6313.0,5351.0,-962.0
3,49.0,Cacoal,78574.0,78574.0,86887.0,8313.0
4,56.0,Cerejeiras,17029.0,17029.0,15890.0,-1139.0
...,...,...,...,...,...,...
5565,22005.0,Vianópolis,12548.0,12548.0,14956.0,2408.0
5566,22054.0,Vicentinópolis,7371.0,7373.0,8768.0,1397.0
5567,22203.0,Vila Boa,4735.0,4735.0,4215.0,-520.0
5568,22302.0,Vila Propício,5145.0,5145.0,5815.0,670.0
5569,108.0,Brasília,2570160.0,2572159.0,2817381.0,247221.0

In [95]:
pormunicipi = pormunicipi.sort_values(by='diferença', ascending=False)
pormunicipi

,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferença
111,2603.0,Manaus,1802014.0,1802014.0,2063689.0,261675.0
5569,108.0,Brasília,2570160.0,2572159.0,2817381.0,247221.0
3829,50308.0,São Paulo,11253503.0,11253503.0,11451999.0,198496.0
3848,52205.0,Sorocaba,586625.0,586816.0,723682.0,137057.0
5417,8707.0,Goiânia,1302001.0,1301912.0,1437366.0,135365.0
...,...,...,...,...,...,...
4931,14902.0,Porto Alegre,1409351.0,1409351.0,1332845.0,-76506.0
169,1402.0,Belém,1393399.0,1393399.0,1303403.0,-89996.0
3247,4904.0,São Gonçalo,999728.0,999728.0,896744.0,-102984.0
3242,4557.0,Rio de Janeiro,6320446.0,6320446.0,6211223.0,-109223.0
2162,27408.0,Salvador,2675656.0,2675656.0,2417678.0,-257978.0

In [96]:
pormunicipi.to_csv(r"H:\python\analise_de_dados\Ctabelaminhaatividade4municipio.csv", sep =";")